import { hashString } from "@/lib/house/rng";
import type { AgentContract, AgentId } from "./types";

const CERTIFIED = "2026-04-01T00:00:00Z";
const EVAL = "claimflow-vertical-v1";

function contract(partial: Omit<AgentContract, "provenance"> & { code: string }): AgentContract {
  return {
    ...partial,
    provenance: {
      code_hash: hashString(partial.code).toString(16),
      model_versions: { overlay: "orpaynter-mas-swarm/1.0" },
      eval_set_id: EVAL,
      certified_at: CERTIFIED,
      certified_by: "orpaynter-mas-swarm",
    },
  };
}

const BASE_KILL = "Operator Stop. Orchestrator freeze. Envelope revoke.";

export const CONTRACTS: AgentContract[] = [
  contract({
    code: "orch-v1",
    id: "claimflow-orchestrator",
    name: "ClaimFlow Orchestrator",
    role: "orchestrator",
    version: "1.0.0",
    objective: "Route ClaimFlow stages. Emit DecisionPackages. Never execute a side-effect without a gate.",
    tools: ["route", "emit-package", "kill", "escalate"],
    data_scope: { tables: ["swarm_log", "decision_package"], write_allowed: true, tenant_required: true },
    authority_scope: {
      max_risk_score: 100,
      allowed_actions: ["route", "emit", "kill", "ledger"],
      forbidden_actions: ["file-claim", "pay", "bind-authority"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants", "claimflow-vertical-slice"],
    decision_package_template: "claimflow-side-effect-v1",
    success_criteria: ["Every write has a package", "Kill tested", "State reconstructible from log"],
    failure_modes: ["ungated write", "hidden blackboard", "self-bind authority"],
    escalation_path: "Named operator. Dual gate if risk ≥ 70.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["route", "gate", "kill"], improvement_gate: "human" },
  }),
  contract({
    code: "intake-v1",
    id: "intake-geocoder",
    name: "Intake",
    role: "claims-intake",
    version: "1.0.0",
    objective: "Normalize a typed US address. Never pick the house.",
    tools: ["geocode"],
    data_scope: { tables: [], write_allowed: false, tenant_required: true },
    authority_scope: {
      max_risk_score: 20,
      allowed_actions: ["read-geocode"],
      forbidden_actions: ["write", "file-claim", "external-message"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants"],
    decision_package_template: "none-read-only",
    success_criteria: ["Place matches typed city", "House number stamped"],
    failure_modes: ["wrong locality", "invented pin"],
    escalation_path: "Operator retypes the address.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["geocode-hit", "geocode-miss"], improvement_gate: "human" },
  }),
  contract({
    code: "storm-v1",
    id: "storm-intel",
    name: "Storm intel",
    role: "triage",
    version: "1.0.0",
    objective: "Attach public storm context. Hail path is modeled.",
    tools: ["nws", "iem-lsr"],
    data_scope: { tables: [], write_allowed: false, tenant_required: true },
    authority_scope: {
      max_risk_score: 25,
      allowed_actions: ["read-weather"],
      forbidden_actions: ["write", "damage-determination"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants", "exposure-not-damage"],
    decision_package_template: "none-read-only",
    success_criteria: ["Source labeled nws|lsr|local"],
    failure_modes: ["treating tiles as dated hail-pass"],
    escalation_path: "Operator picks another cell.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["cell-attach"], improvement_gate: "human" },
  }),
  contract({
    code: "foot-v1",
    id: "footprint-surveyor",
    name: "Footprint",
    role: "evidence",
    version: "1.0.0",
    objective: "Pull OSM / USA Structures / Microsoft rings. Label fidelity.",
    tools: ["osm", "usa-structures", "ms-footprints"],
    data_scope: { tables: [], write_allowed: false, tenant_required: true },
    authority_scope: {
      max_risk_score: 30,
      allowed_actions: ["read-footprint"],
      forbidden_actions: ["write", "invent-outline"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants", "model-disclaimer"],
    decision_package_template: "none-read-only",
    success_criteria: ["Source labeled", "Estimated never mixed as measured"],
    failure_modes: ["fake house as real"],
    escalation_path: "Operator rejects the lot.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["outline-source"], improvement_gate: "human" },
  }),
  contract({
    code: "est-v1",
    id: "inspector-estimator",
    name: "Estimator",
    role: "estimator",
    version: "1.0.0",
    objective: "Draft a DecisionPackage estimate from modeled concerns. Never file.",
    tools: ["scan", "line-items"],
    data_scope: { tables: ["decision_package"], write_allowed: false, tenant_required: true },
    authority_scope: {
      max_risk_score: 39,
      allowed_actions: ["propose-estimate"],
      forbidden_actions: ["approve", "file-claim", "dispatch", "pay"],
      roles: ["operator", "reviewer"],
    },
    policy_refs: ["AIA-invariants", "orpaynter-decision-package", "exposure-not-damage"],
    decision_package_template: "claimflow-side-effect-v1",
    success_criteria: ["Line items linked to modeled parts", "Risk ≥ 40 forces human gate"],
    failure_modes: ["treating draft as determination"],
    escalation_path: "Named reviewer on the estimate tab.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["draft-estimate"], improvement_gate: "human" },
  }),
  contract({
    code: "pol-v1",
    id: "policy-compliance",
    name: "Policy",
    role: "compliance",
    version: "1.0.0",
    objective: "Default-deny. Same area number. Block filing without evidence.",
    tools: ["policy-check"],
    data_scope: { tables: ["decision_package"], write_allowed: false, tenant_required: true },
    authority_scope: {
      max_risk_score: 20,
      allowed_actions: ["flag-gap", "block"],
      forbidden_actions: ["override-policy", "file-claim"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants", "default-deny"],
    decision_package_template: "claimflow-side-effect-v1",
    success_criteria: ["Missing evidence listed", "No silent approve"],
    failure_modes: ["always-approve"],
    escalation_path: "Operator reject or request evidence.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["gap-flag"], improvement_gate: "human" },
  }),
  contract({
    code: "log-v1",
    id: "logistics-scout",
    name: "Logistics",
    role: "fulfillment",
    version: "1.0.0",
    objective: "Propose crews and yards. Do not move them.",
    tools: ["places", "osm-pois"],
    data_scope: { tables: [], write_allowed: false, tenant_required: true },
    authority_scope: {
      max_risk_score: 35,
      allowed_actions: ["propose-crew"],
      forbidden_actions: ["dispatch", "purchase", "message-vendor"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants", "default-deny"],
    decision_package_template: "claimflow-side-effect-v1",
    success_criteria: ["POI source labeled", "Area code present"],
    failure_modes: ["auto-dispatch"],
    escalation_path: "Issue authority on the crews panel.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["poi-propose"], improvement_gate: "human" },
  }),
  contract({
    code: "learn-v1",
    id: "learning-ledger",
    name: "Ledger",
    role: "learning",
    version: "1.0.0",
    objective: "Append accuracy records. Propose improvements. Never self-deploy.",
    tools: ["ledger-append", "propose-improve"],
    data_scope: { tables: ["accuracy_ledger"], write_allowed: true, tenant_required: true },
    authority_scope: {
      max_risk_score: 15,
      allowed_actions: ["append-record", "propose"],
      forbidden_actions: ["rewrite-prompt", "bind-authority", "deploy"],
      roles: ["operator"],
    },
    policy_refs: ["AIA-invariants", "recursive-learning-loop"],
    decision_package_template: "improvement-v1",
    success_criteria: ["Append-only", "Improvement gated human"],
    failure_modes: ["silent self-update"],
    escalation_path: "Human gate on any prompt or policy change.",
    kill_switch: BASE_KILL,
    recursive_learning: { telemetry_events: ["accuracy", "improve-propose"], improvement_gate: "human" },
  }),
];

export const CONTRACT_BY_ID: Record<AgentId, AgentContract> = Object.fromEntries(
  CONTRACTS.map((c) => [c.id, c]),
) as Record<AgentId, AgentContract>;
